# Complete Docker Compose Setup for Sell Your Ebook
# Includes Astro SSG + Flask Config Editor
# https://github.com/JAlcocerT/Docker/tree/main/Web/SSGs/Astro

services:
  # Astro Development Server
  astro-dev:
    image: node:22.16-alpine3.22
    container_name: astro-dev
    working_dir: /app
    ports:
      - "4321:4321"  # Astro dev server with live changes
    volumes:
      - ./landing-page-book-astro-tailwind:/app
      - node_modules_dev:/app/node_modules  # Named volume for node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 4321"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
    networks:
      - project-sellyourebook
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Astro Production Build & Serve
  astro-prod:
    image: node:22.16-alpine3.22
    container_name: astro-prod
    working_dir: /app
    volumes:
      - ./landing-page-book-astro-tailwind:/app
      - node_modules_prod:/app/node_modules  # Named volume for node_modules
    ports:
      - "8090:4321"  # Production server on port 8090
    command: >
      sh -c "npm install && 
      npm run build && 
      npx http-server ./dist -p 4321 -a 0.0.0.0"
    environment:
      - NODE_ENV=production
      - PORT=4321
    networks:
      - project-sellyourebook
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Flask Config Editor
  config-editor:
    image: python:3.11-slim
    container_name: config-editor
    working_dir: /app
    ports:
      - "5000:5000"  # Flask app on port 5000
      #- "0.0.0.0:5000:5000"  # Explicitly bind to all interfaces
    volumes:
      - ./config-editor:/app
      - ./landing-page-book-astro-tailwind/src:/app/config  # Mount config directory
    command: sh -c "pip install -r requirements.txt && python app.py"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    networks:
      - project-sellyourebook
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Complete Development Stack (Astro + Config Editor)
  dev-stack:
    image: node:22.16-alpine3.22
    container_name: dev-stack
    working_dir: /app
    ports:
      - "4321:4321"  # Astro dev server
      - "5000:5000"  # Flask config editor
    volumes:
      - ./landing-page-book-astro-tailwind:/app
      - ./config-editor:/config-editor
      - node_modules_dev:/app/node_modules
    command: >
      sh -c "
      echo 'Starting complete development stack...' &&
      echo 'Installing Astro dependencies...' &&
      npm install &&
      echo 'Installing Flask dependencies...' &&
      cd /config-editor && pip install -r requirements.txt &&
      echo 'Starting Flask config editor in background...' &&
      python app.py &
      echo 'Starting Astro development server...' &&
      cd /app && npm run dev -- --host 0.0.0.0 --port 4321
      "
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - project-sellyourebook
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  node_modules_dev:
  node_modules_prod:

networks:
  project-sellyourebook:
    driver: bridge